apiVersion: v1
entries:
  hl7-resource-generator:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2021-06-25T09:00:11.433068-05:00"
    description: A Helm Chart to deploy the Alvearie HL7 Resource Generator service.  This service will convert HL7 data to FHIR.
    digest: 54b9ab79dfad661c817fe9b7b028f39570f07787141fa904b49a678e93214a44
    home: https://github.com/Alvearie/hl7-resource-generator-service
    keywords:
    - ibm
    - alvearie
    - hl7
    - fhir
    maintainers:
    - email: pbhallam@us.ibm.com
      name: Pushpa Bhallamudi
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: hl7-resource-generator
    type: application
    urls:
    - hl7-resource-generator-0.1.0.tgz
    version: 0.1.0
generated: "2021-06-25T09:00:11.432465-05:00"
