apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hl7-resource-generator.fullname" . }}
  labels:
    {{- include "hl7-resource-generator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "hl7-resource-generator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "hl7-resource-generator.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: hl7-resource-generator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
          - name: http
            containerPort: {{ .Values.service.port }}
            protocol: TCP