apiVersion: v1
entries:
  hl7-resource-generator:
  - apiVersion: v2
    appVersion: 0.0.1
    created: "2021-07-01T08:11:02.759075-05:00"
    description: A Helm Chart to deploy the Alvearie HL7 Resource Generator service.  This service will convert HL7 data to FHIR.
    digest: edc7c1305a89d4ce2c8b8ef8ec92dd170bbd8f440ee3e4663e0b8c68ee8f1409
    home: https://github.com/Alvearie/hl7-resource-generator-service
    keywords:
    - ibm
    - alvearie
    - hl7
    - fhir
    maintainers:
    - email: pbhallam@us.ibm.com
      name: Pushpa Bhallamudi
    - email: atclark@us.ibm.com
      name: Adam T. Clark
    name: hl7-resource-generator
    type: application
    urls:
    - hl7-resource-generator-0.1.0.tgz
    version: 0.1.0
generated: "2021-07-01T08:11:02.758503-05:00"
